name: Deploy to Hostinger

on:
  push:
    branches:
      - master  # Replace with your main branch if different
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pages  # Environment that contains the secrets

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Specify the Node.js version
          cache: 'npm'  # Enable caching for faster builds

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci  # Clean install from lockfile

      # Step 4: Build the project
      - name: Build Project
        run: npm run build  # Build the application

      # Step 5: Verify the build output directory
      - name: Verify Build Output
        run: |
          echo "Build output files:"
          ls -l dist  # Check if the dist folder exists and contains files

      # Step 6: Deploy to Hostinger via FTP
      - name: Deploy to Hostinger via SFTP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.FTP_SERVER }}  # Add the Hostinger server IP or domain
          username: ${{ secrets.FTP_USERNAME }}  # Your FTP username
          password: ${{ secrets.FTP_PASSWORD }}  # Your FTP password
          source: dist/*  # The build output
          target: /public_html/  # The target directory on the server

