# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Hostinger

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    environment: pages

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build

    - name: Verify build output
      run: |
        echo "Contents of dist/ folder:"
        ls -la dist/

    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/  # Ensure the build folder exists and has a trailing slash
        server-dir: /public_html/
        protocol: ftps
        debug: true
        
