name: Deploy Static Content to Hostinger

on:
  push:
    branches:
      - master  # Replace with your main branch if different
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pages # Specify the environment that contains the secrets
    
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Adjust Node.js version as needed
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the project
      - name: Build project
        run: npm run build

      # Step 5: Verify the build output directory
      - name: Check build output
        run: |
          echo "Build output:"
          ls -l dist  # Ensure the dist folder exists and contains files

      # Step 6: Deploy to Hostinger via FTP
      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.2  # Use a valid version
        with:
          server: ${{ secrets.FTP_SERVER }}  # Add FTP server address to GitHub Secrets
          username: ${{ secrets.FTP_USERNAME }}  # Add FTP username to GitHub Secrets
          password: ${{ secrets.FTP_PASSWORD }}  # Add FTP password to GitHub Secrets
          local-dir: dist  # Directory containing the build output
          server-dir: /public_html/  # Target directory on the server
