name: Deploy static content to Hostinger

on:
  push:
    branches: ['main']  # Replace with your default branch if needed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Verify build output directory
        run: ls -l ./dist  # Ensure this matches your actual build output directory

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.2
        with:
          server: ftp.balticcodes.com  # Hostinger FTP server IP
          username: ${{ secrets.FTP_USERNAME }}  # Reference the FTP_USERNAME secret
          password: ${{ secrets.FTP_PASSWORD }}  # Reference the FTP_PASSWORD secret
          local-dir: ./dist  # Directory containing the build output
          server-dir: /public_html  # Target directory on the server
