name: Deploy static content to Hostinger

on:
  push:
    branches: ['main']  # Replace with your default branch if needed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Verify build output directory
        run: ls -l ./dist  # Ensure this matches your actual build output directory

      - name: Deploy to Hostinger via FTP
        uses: lukaszgoc/ftpupload-action@v2.0.0
        with:
          host: 45.84.207.247  # Hostinger FTP server IP
          username: ${{ secrets.FTP_USERNAME }}  # Your Hostinger FTP username from GitHub Secrets
          password: ${{ secrets.FTP_PASSWORD }}  # Your Hostinger FTP password from GitHub Secrets
          localDir: ./dist  # Path to the directory containing your built files
          remoteDir: /public_html  # Target directory on the server
